export const ErrorCode = {
  // Project
  PROJ_NOT_FOUND: 'PROJ_NOT_FOUND',
  // Task
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  // Member
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBER_INVALID_RATE: 'MEMBER_INVALID_RATE',
  // EVM
  EVM_INVALID_BASE_DATE: 'EVM_INVALID_BASE_DATE',
  EVM_PV_ZERO: 'EVM_PV_ZERO',
  EVM_INVALID_AVAILABILITY_RATE: 'EVM_INVALID_AVAILABILITY_RATE',
  EVM_CIRCULAR_DEPENDENCY: 'EVM_CIRCULAR_DEPENDENCY',
  // Import
  IMPORT_INVALID_YAML: 'IMPORT_INVALID_YAML',
  IMPORT_PARSE_ERROR: 'IMPORT_PARSE_ERROR',
  IMPORT_MISSING_FIELD: 'IMPORT_MISSING_FIELD',
  // Snapshot (Progress Tracking)
  SNAP_TASK_NOT_FOUND: 'SNAP_TASK_NOT_FOUND',
} as const

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode]
