export const EVM = {
  ink: '#1c1a16',
  ink2: '#4a463d',
  ink3: '#827d70',
  ink4: '#b1ab9d',
  rule: '#e4dfd2',
  ruleSoft: '#efebde',
  paper: '#f7f4ec',
  paperWarm: '#fbf9f2',
  card: '#ffffff',
  brand: '#9bc132',
  brandDeep: '#7ea61f',
  brandSoft: '#e8f1cd',
  brandWash: 'rgba(155,193,50,0.10)',
  ok: '#5d8a3a',
  okSoft: '#dfe9cf',
  warn: '#c89a2d',
  warnSoft: '#f3e7c4',
  crit: '#b8482e',
  critSoft: '#f1d5c8',
  na: '#9a958a',
  font: "'Inter', 'Helvetica Neue', -apple-system, BlinkMacSystemFont, system-ui, sans-serif",
  fontSerif: "'Source Serif 4', 'Source Serif Pro', 'Hiragino Mincho ProN', serif",
  fontBrand: "'Cinzel', 'Trajan Pro', 'Source Serif 4', serif",
  fontMono: "'JetBrains Mono', ui-monospace, monospace",
} as const

export type EvmToken = typeof EVM
